import '../models/message_model.dart';

Map<String, List<MessageModel>> messagesMap = {
  "Zagreus": [
    MessageModel(message: "Father won't stop yelling again 😤", time: "9:00 AM", isMe: true),
    MessageModel(message: "Stay focused, boy.", time: "9:01 AM", isMe: false, profileImage: 'assets/icons/zag.jpg'),
    MessageModel(message: "I'll try...", time: "9:02 AM", isMe: true),
    MessageModel(message: "Another failed escape, huh?", time: "9:05 AM", isMe: false, profileImage: 'assets/icons/zag.jpg'),
    MessageModel(message: "Yeah... but I'm learning.", time: "9:07 AM", isMe: true),
    MessageModel(message: "Good. Never stop.", time: "9:08 AM", isMe: false, profileImage: 'assets/icons/zag.jpg'),
    MessageModel(message: "Nyx has been guiding me too.", time: "9:10 AM", isMe: true),
    MessageModel(message: "The House relies on her wisdom.", time: "9:11 AM", isMe: false, profileImage: 'assets/icons/zag.jpg'),
    MessageModel(message: "I'm heading back out.", time: "9:13 AM", isMe: true),
    MessageModel(message: "Try not to disappoint... again.", time: "9:14 AM", isMe: false, profileImage: 'assets/icons/zag.jpg'),
  ],

  "Hades": [
    MessageModel(message: "Back again, are you?", time: "10:15 AM", isMe: false, profileImage: 'assets/icons/hades.jpg'),
    MessageModel(message: "You know me... never giving up 😈", time: "10:16 AM", isMe: true),
    MessageModel(message: "Persistent fool.", time: "10:17 AM", isMe: false, profileImage: 'assets/icons/hades.jpg'),
    MessageModel(message: "One day I'll prove you wrong.", time: "10:19 AM", isMe: true),
    MessageModel(message: "Hmph. Doubtful.", time: "10:20 AM", isMe: false, profileImage: 'assets/icons/hades.jpg'),
    MessageModel(message: "You underestimate me.", time: "10:21 AM", isMe: true),
    MessageModel(message: "As always.", time: "10:22 AM", isMe: false, profileImage: 'assets/icons/hades.jpg'),
    MessageModel(message: "You'll see, old man.", time: "10:23 AM", isMe: true),
    MessageModel(message: "If I cared, perhaps.", time: "10:24 AM", isMe: false, profileImage: 'assets/icons/hades.jpg'),
    MessageModel(message: "Typical...", time: "10:25 AM", isMe: true),
  ],

  "Nyx": [
    MessageModel(message: "Mother Nyx, I had strange dreams again.", time: "11:00 AM", isMe: true),
    MessageModel(message: "Dreams are but reflections, my child.", time: "11:01 AM", isMe: false, profileImage: 'assets/icons/nyx.jpg'),
    MessageModel(message: "Do not fear them.", time: "11:02 AM", isMe: false, profileImage: 'assets/icons/nyx.jpg'),
    MessageModel(message: "They felt... real.", time: "11:03 AM", isMe: true),
    MessageModel(message: "Even illusions hold truth.", time: "11:04 AM", isMe: false, profileImage: 'assets/icons/nyx.jpg'),
    MessageModel(message: "I trust your wisdom.", time: "11:05 AM", isMe: true),
    MessageModel(message: "You are strong enough for this path.", time: "11:06 AM", isMe: false, profileImage: 'assets/icons/nyx.jpg'),
    MessageModel(message: "I’ll try to be.", time: "11:07 AM", isMe: true),
    MessageModel(message: "The darkness guides you, Zagreus.", time: "11:08 AM", isMe: false, profileImage: 'assets/icons/nyx.jpg'),
    MessageModel(message: "Thank you... always.", time: "11:09 AM", isMe: true),
  ],

  "Hypnos": [
    MessageModel(message: "Oh hey! Another death, huh?", time: "12:30 PM", isMe: false, profileImage: 'assets/icons/hyp.webp'),
    MessageModel(message: "Not helping, Hypnos...", time: "12:31 PM", isMe: true),
    MessageModel(message: "😅 Sorry! Next time dodge better!", time: "12:32 PM", isMe: false, profileImage: 'assets/icons/hyp.webp'),
    MessageModel(message: "I know... I know...", time: "12:33 PM", isMe: true),
    MessageModel(message: "You almost made it past Elysium though!", time: "12:34 PM", isMe: false, profileImage: 'assets/icons/hyp.webp'),
    MessageModel(message: "Not exactly helpful commentary.", time: "12:35 PM", isMe: true),
    MessageModel(message: "Hey, I'm rooting for you! 😇", time: "12:36 PM", isMe: false, profileImage: 'assets/icons/hyp.webp'),
    MessageModel(message: "Sure you are...", time: "12:37 PM", isMe: true),
    MessageModel(message: "Good luck next time! You'll need it!", time: "12:38 PM", isMe: false, profileImage: 'assets/icons/hyp.webp'),
    MessageModel(message: "Thanks... I guess.", time: "12:39 PM", isMe: true),
  ],

  "Achilles": [
    MessageModel(message: "Achilles, got any training tips?", time: "1:45 PM", isMe: true),
    MessageModel(message: "Discipline, Prince. Focus on your form.", time: "1:46 PM", isMe: false, profileImage: 'assets/icons/ach.jpg'),
    MessageModel(message: "Noted. Thanks, friend.", time: "1:47 PM", isMe: true),
    MessageModel(message: "Never forget your footwork.", time: "1:48 PM", isMe: false, profileImage: 'assets/icons/ach.jpg'),
    MessageModel(message: "It’s improving.", time: "1:49 PM", isMe: true),
    MessageModel(message: "Control your breathing under pressure.", time: "1:50 PM", isMe: false, profileImage: 'assets/icons/ach.jpg'),
    MessageModel(message: "Trying my best!", time: "1:51 PM", isMe: true),
    MessageModel(message: "You’re getting there.", time: "1:52 PM", isMe: false, profileImage: 'assets/icons/ach.jpg'),
    MessageModel(message: "Thanks for always having my back.", time: "1:53 PM", isMe: true),
    MessageModel(message: "It’s an honor, Prince.", time: "1:54 PM", isMe: false, profileImage: 'assets/icons/ach.jpg'),
  ],

  "Dusa": [
    MessageModel(message: "H-hi Lord Zagreus! Need anything? 😳", time: "2:00 PM", isMe: false, profileImage: 'assets/icons/dusa.jpg'),
    MessageModel(message: "No worries, Dusa. Just checking in.", time: "2:01 PM", isMe: true),
    MessageModel(message: "You're s-so kind! 🥰", time: "2:02 PM", isMe: false, profileImage: 'assets/icons/dusa.jpg'),
    MessageModel(message: "How’s cleaning duty?", time: "2:03 PM", isMe: true),
    MessageModel(message: "M-messy as always! 😅", time: "2:04 PM", isMe: false, profileImage: 'assets/icons/dusa.jpg'),
    MessageModel(message: "Let me know if I can help.", time: "2:05 PM", isMe: true),
    MessageModel(message: "R-really? That’d be amazing! 🧹", time: "2:06 PM", isMe: false, profileImage: 'assets/icons/dusa.jpg'),
    MessageModel(message: "Anytime, Dusa.", time: "2:07 PM", isMe: true),
    MessageModel(message: "Y-you’re the best! 💚", time: "2:08 PM", isMe: false, profileImage: 'assets/icons/dusa.jpg'),
    MessageModel(message: "Stay safe.", time: "2:09 PM", isMe: true),
  ],

  "Megaera": [
    MessageModel(message: "Escaping again, Zagreus?", time: "3:20 PM", isMe: false, profileImage: 'assets/icons/meg.webp'),
    MessageModel(message: "What else is new, Meg? 😉", time: "3:21 PM", isMe: true),
    MessageModel(message: "One day I'll stop you for good.", time: "3:22 PM", isMe: false, profileImage: 'assets/icons/meg.webp'),
    MessageModel(message: "Doubt it.", time: "3:23 PM", isMe: true),
    MessageModel(message: "You’re testing my patience.", time: "3:24 PM", isMe: false, profileImage: 'assets/icons/meg.webp'),
    MessageModel(message: "And your skills.", time: "3:25 PM", isMe: true),
    MessageModel(message: "Be careful what you wish for.", time: "3:26 PM", isMe: false, profileImage: 'assets/icons/meg.webp'),
    MessageModel(message: "I’m ready anytime.", time: "3:27 PM", isMe: true),
    MessageModel(message: "Next time... no mercy.", time: "3:28 PM", isMe: false, profileImage: 'assets/icons/meg.webp'),
    MessageModel(message: "Looking forward to it.", time: "3:29 PM", isMe: true),
  ],

  "Thanatos": [
    MessageModel(message: "You survived longer than usual this time.", time: "4:00 PM", isMe: false, profileImage: 'assets/icons/than.png'),
    MessageModel(message: "Getting stronger, Than.", time: "4:01 PM", isMe: true),
    MessageModel(message: "Hmph. Don't get cocky.", time: "4:02 PM", isMe: false, profileImage: 'assets/icons/than.png'),
    MessageModel(message: "Just saying, I’m improving.", time: "4:03 PM", isMe: true),
    MessageModel(message: "We’ll see in the next run.", time: "4:04 PM", isMe: false, profileImage: 'assets/icons/than.png'),
    MessageModel(message: "Game on. 😈", time: "4:05 PM", isMe: true),
    MessageModel(message: "Try not to get killed next time.", time: "4:06 PM", isMe: false, profileImage: 'assets/icons/than.png'),
    MessageModel(message: "No promises.", time: "4:07 PM", isMe: true),
    MessageModel(message: "Typical.", time: "4:08 PM", isMe: false, profileImage: 'assets/icons/than.png'),
    MessageModel(message: "See you soon, Than.", time: "4:09 PM", isMe: true),
  ],
};
